# Try to solve XOR problem with Neural Network

Input layer has 3 nodes <br>
Hidden layer has 2 nodes : w_0 is a 3x2 matrix <br>
Output layer has 1 node  : w_1 is a 2x1 matrix <br>
No bias term

In [1]:
import numpy as np
import torch
np.random.seed(1)

In [2]:
# input dataset, in matrix form
# X3 is irrelevant, the XOR signal is from X1 and X2
#x = torch.tensor([[0,0,1], [0,1,1],[1,0,1],[1,1,1]],dtype = torch.double)
x = np.array([[0,0,1], [0,1,1],[1,0,1],[1,1,1]])

In [3]:
#convert from numpy array to torch tensor
x = torch.from_numpy(x)

In [4]:
#set torch tensor to float64 data type
x = x.double()
x

tensor([[ 0.,  0.,  1.],
        [ 0.,  1.,  1.],
        [ 1.,  0.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)

In [5]:
y = np.array([[0,1,1,0]]).T
y = torch.from_numpy(y)
y = y.double()
y

tensor([[ 0.],
        [ 1.],
        [ 1.],
        [ 0.]], dtype=torch.float64)

In [6]:
x

tensor([[ 0.,  0.,  1.],
        [ 0.,  1.,  1.],
        [ 1.,  0.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)

In [7]:
y

tensor([[ 0.],
        [ 1.],
        [ 1.],
        [ 0.]], dtype=torch.float64)

In [8]:
#sigmoid function 
def sigmoid(x):
    return 1.0/(1+torch.exp(-x))

In [51]:
learning_rate = 1e-2

In [53]:
# initialize weights randomly 
# if w is a Tensor with requires_grad = True then
#after backpropagation w.grad will be another Tensor holding the gradient of x

#ReLU activation: only converge at eta = 1e-3
#interesting point : for 2 hidden nodes, the NN will not converge (Try it yourself) 
#                    at 10 hidden nodes, the NN will converge 

#Sigmoid activation: converge at eta = 5e-1
#interesting point : for 2 hidden nodes, the NN WILL converge (Try it yourself) 

w1 = torch.rand(3,2, requires_grad = True,dtype = torch.double) 
w2 = torch.rand(2,1, requires_grad = True,dtype = torch.double)

#Lesson: Re
#gradient descent step:
for i in range (50000):
    #forward pass: go from input layer to output layer
    #y_pred = x.mm(w1).clamp(min=0).mm(w2)
    y_pred = sigmoid(x.mm(w1)).mm(w2)
    
    #compute and print the loss
    loss = (y_pred-y).pow(2).sum()
    if (i%10000 == 0):
        print(i,loss.item())
        
    #note that loss is a scalar
    loss.backward()
    
    #compute the gradient using autograd backprop from Pytorch
    with torch.no_grad():
        #update weights
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        #zero out the gradient
        w1.grad.zero_()
        w2.grad.zero_()
        

0 2.270323043439472
10000 3.965309805831293e-05
20000 2.851154365205394e-16
30000 4.277364065479699e-27
40000 4.277364065479699e-27


In [54]:
y_pred

tensor([[ 3.3196e-14],
        [ 1.0000e+00],
        [ 1.0000e+00],
        [ 3.9968e-14]], dtype=torch.float64)

In [189]:
w1

tensor([[ 3.6963,  1.3268],
        [ 3.7856,  1.3463],
        [-1.2793, -1.6572]], dtype=torch.float64)

In [190]:
w2

tensor([[ 2.8593],
        [-3.8868]], dtype=torch.float64)